yarnPath: .yarn/releases/yarn-3.3.1.cjs
nodeLinker: node-modules
# pnpMode: loose

# packageExtensions:
#   "@firebase/auth@*":
#     dependencies:
#       "@firebase/app": "*"
#       "@firebase/app-types": "*"
#   "@firebase/database@*":
#     peerDependencies:
#       "@firebase/app": "*"
#       "@firebase/app-types": "*"
#   unplugin-vue-router@*:
#     dependencies:
#       "@vue/compiler-sfc": "*"
