// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/components/admin/Item/AddItem.vue')['default']
    AddItemToTab: typeof import('./src/components/userPage/AddItemToTab.vue')['default']
    ClearTab: typeof import('./src/components/admin/User/ClearTab.vue')['default']
    DeleteItem: typeof import('./src/components/admin/Item/DeleteItem.vue')['default']
    DeleteItemFromTab: typeof import('./src/components/userPage/DeleteItemFromTab.vue')['default']
    FeedBack: typeof import('./src/components/FeedBack.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ItemCard: typeof import('./src/components/admin/Item/ItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToggleRole: typeof import('./src/components/admin/User/ToggleRole.vue')['default']
    UserCard: typeof import('./src/components/admin/User/UserCard.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
