// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddItemToTab: typeof import('./src/components/userPage/AddItemToTab.vue')['default']
    ClearHistory: typeof import('./src/components/admin/User/ClearHistory.vue')['default']
    ClearTab: typeof import('./src/components/ClearTab.vue')['default']
    DeleteItem: typeof import('./src/components/admin/Item/DeleteItem.vue')['default']
    DeleteItemFromTab: typeof import('./src/components/userPage/DeleteItemFromTab.vue')['default']
    FeedBack: typeof import('./src/components/FeedBack.vue')['default']
    ItemCard: typeof import('./src/components/admin/Item/ItemCard.vue')['default']
    MdiAccountCog: typeof import('~icons/mdi/account-cog')['default']
    MdiArchiveCog: typeof import('~icons/mdi/archive-cog')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiLogout: typeof import('~icons/mdi/logout')['default']
    MdiMessageAlertOutline: typeof import('~icons/mdi/message-alert-outline')['default']
    MdiPlusThick: typeof import('~icons/mdi/plus-thick')['default']
    MdiSecurity: typeof import('~icons/mdi/security')['default']
    MdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    NewItem: typeof import('./src/components/admin/Item/NewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleRole: typeof import('./src/components/admin/User/ToggleRole.vue')['default']
    UserCard: typeof import('./src/components/admin/User/UserCard.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
